apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: cron-scaledobject
  namespace: default
spec:
  scaleTargetRef:
    name: nginx
  triggers:
  - type: cron
    metadata:
      timezone: Asia/Tokyo
      start: 25 * * * *
      end: 30 * * * *
      desiredReplicas: "10"