apiVersion: skaffold/v4beta2
kind: Config
metadata:
  name: skaffold
build:
  artifacts:
  - image: skaffold-hands-on
    docker:
      dockerfile: Dockerfile
manifests:
  rawYaml:
  - manifest/k8s-deploy.yaml
  - manifest/k8s-svc.yaml
