apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-keda
  namespace: default
  # labels:
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-keda
  template:
    metadata:
      labels:
        app: demo-keda
    spec:
      containers:
      - name: demo-keda
        image: 109923486398.dkr.ecr.ap-northeast-1.amazonaws.com/demo-keda:latest
        env:
        - name: ACCOUNT_ID
          value: "109923486398"
        - name: REGION
          value: "ap-northeast-1"
